version: "3"
services:
  node:
    container_name: node
    tty: true
    build: ./node
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
  mongo:
    container_name: mongo
    env_file: .env
    image: mongo
    restart: always
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27107
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  mongo-express:
    container_name: mongo-express
    env_file: .env
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
    links:
      - mongo

